services:
  backend:
    image: $ECR_SERVER_URL:$BRANCH-$SHA
    container_name: backend
    depends_on:
      db:
        condition: service_healthy
    ports:
      - $BACKEND_PORT:8080
    healthcheck:
      test: ["CMD-SHELL", "nc -z backend $BACKEND_PORT || exit 1"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    environment:
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - AWS_REGION=ap-southeast-1
    network_mode: "host"

  db:
    image: mysql:8.0.39
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: dka_shop
      MYSQL_USER: mysql
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - $DB_PORT:3306
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -padmin"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
