services:
  backend:
    image: $ECR_SERVER_URL:$BRANCH-$SHA
    container_name: backend
    working_dir: /run
    ports:
      - $BACKEND_PORT:8080
    depends_on:
      postgres:
        condition: service_healthy
      auth-server:
        condition: service_healthy
    env_file:
      - .env.be
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost $BACKEND_PORT || exit 1"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    environment:
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - AWS_REGION=ap-southeast-1
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
