services:
  backend:
    image: $ECR_SERVER_URL:$BRANCH-$SHA
    container_name: backend
    depends_on:
      db:
        condition: service_healthy
    ports:
      - $BACKEND_PORT:8080
    healthcheck:
      test: ["CMD-SHELL", "nc -z backend $BACKEND_PORT || exit 1"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    environment:
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - AWS_REGION=ap-southeast-1
    networks:
      - app-network
      
networks:
  app-network:
    external: true
