name: CICD

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  dev-CI:
    if: github.ref == 'refs/heads/develop'
    uses: Dummy-WAD/dka-shop-be/.github/workflows/dev-CI.yml@DEK-63-Implement-CI-CD-pipeline
    secrets: inherit
  dev-CD:
    if: github.ref == 'refs/heads/develop'
    needs: dev-CI
    uses: Dummy-WAD/dka-shop-be/.github/workflows/dev-CD.yml@DEK-63-Implement-CI-CD-pipeline


  staging-CI:
      if: github.ref == 'refs/heads/staging'
      uses: Dummy-WAD/dka-shop-be/.github/workflows/staging-CI.yml@DEK-63-Implement-CI-CD-pipeline
      secrets: inherit
  # staging-CD:
  #   if: github.ref == 'refs/heads/staging'
  #   needs: staging-CI
  #   uses: Dummy-WAD/dka-shop-be/.github/workflows/staging-CD.yml@DEK-63-Implement-CI-CD-pipeline


  prod-CI:
    if: github.ref == 'refs/heads/main'
    uses: Dummy-WAD/dka-shop-be/.github/workflows/prod-CI.yml@DEK-63-Implement-CI-CD-pipeline
    secrets: inherit
  # prod-CD:
  #   if: github.ref == 'refs/heads/main'
  #   needs: prod-CI
  #   uses: Dummy-WAD/dka-shop-be/.github/workflows/prod-CD.yml@DEK-63-Implement-CI-CD-pipeline