name: CI Phase Dev

on:
  workflow_call:

jobs:
  build_dev:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      ECR_URL: ${{ secrets.ECR_URL }}
      ECR_SERVER_URL: ${{ secrets.ECR_SERVER_URL }}

      PORT: ${{ secrets.PORT_DEV }}
      REACT_URL: ${{ secrets.REACT_URL_DEV }}

      JWT_SECRET: ${{ secrets.JWT_SECRET_DEV }}
      JWT_ACCESS_EXPIRATION_MINUTES: ${{ secrets.JWT_ACCESS_EXPIRATION_MINUTES }}
      JWT_REFRESH_EXPIRATION_DAYS: ${{ secrets.JWT_REFRESH_EXPIRATION_DAYS }}
      JWT_RESET_PASSWORD_EXPIRATION_MINUTES: ${{ secrets.JWT_RESET_PASSWORD_EXPIRATION_MINUTES }}
      JWT_VERIFY_EMAIL_EXPIRATION_MINUTES: ${{ secrets.JWT_VERIFY_EMAIL_EXPIRATION_MINUTES }}

      NODE_ENV: ${{ secrets.NODE_ENV_DEV }}
      SMTP_HOST: ${{ secrets.SMTP_HOST }}
      SMTP_PORT: ${{ secrets.SMTP_PORT }}
      SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
      SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
      EMAIL_FROM: ${{ secrets.EMAIL_FROM }}

      DB_HOST: ${{ secrets.DB_HOST_DEV }}
      DB_PORT: ${{ secrets.DB_PORT_DEV }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    steps:
      - uses: actions/checkout@v4

      - uses: benjlevesque/short-sha@v3.0
        id: short-sha
        with:
          length: 6

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Check Docker version
        run: docker --version

        # Pre-build server
      - name: Pre-build server
        run: |
          touch .env
          envsubst < .env.example > .env
          npm install

      - name: Migrate Database
        run: |
          cd src/models
          sed -i 's/\$DB_USER/'"$DB_USER"'/g' config/config.json
          sed -i 's/\$DB_PASSWORD/'"$DB_PASSWORD"'/g' config/config.json
          sed -i 's/\$DB_NAME/'"$DB_NAME"'/g' config/config.json
          sed -i 's/\$DB_HOST/'"$DB_HOST"'/g' config/config.json
          cat config/config.json
          chmod +x migration.sh
          ./migration.sh
        continue-on-error: false

      - name: Build Back-end Server
        env:
          SHA: ${{ steps.short-sha.outputs.sha }}
          BRANCH: ${{ steps.extract_branch.outputs.branch }}
        run: |
          pwd
          ls -la 
          docker build -t dek_server:"${{ env.BRANCH }}-${{ env.SHA }}" .
          docker tag dek_server:"${{ env.BRANCH }}-${{ env.SHA }}" "${{ env.ECR_SERVER_URL }}":"${{ env.BRANCH }}-${{ env.SHA }}"
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ env.ECR_URL }}
          docker push "${{ env.ECR_SERVER_URL }}:${{ env.BRANCH }}-${{ env.SHA }}"
        continue-on-error: false
